### ISSUE TITLE
Unable to get it working.

### ISSUE THREAD

**Issue by ToddMaxey** [microsoft/Convert-Etl2Pcapng#3]
After following the installation instructions, everything looks in place but I keep getting the following error:

PS C:\temp> Convert-Etl2Pcapng .\VideoExample.etl
.\etl2pcapng.exe : The term '.\etl2pcapng.exe' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Program Files\WindowsPowerShell\Modules\Convert-Etl2Pcapng\2020.5.14\Convert-Etl2Pcapng.psm1:416 char:13
+             .\etl2pcapng.exe "$($file.FullName)" "$($file.DirectoryNa ...
+             ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\etl2pcapng.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I modified the Convert-Etl2Pcapng.psm1 file and removed the '.\\' at line 411 and 416 and the conversion would work from Convert-Etl2Pcapng and the right click.

**Comment by JamesKehr** [comment]
@ToddMaxey, I apologize for just now seeing this. My notification never showed up.

What version of PowerShell are you using? I haven't seen this on Windows PowerShell 5.1 or PowerShell 7+.

Normally, with PowerShell, you need the ".\\" to run an EXE that isn't in the system or user PATH. Which makes your behavior very curious.

For example (same error on 5.1 and 7.1.3):

```
> etl2pcapng -?
etl2pcapng : The term 'etl2pcapng' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ etl2pcapng -?
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (etl2pcapng:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: The command etl2pcapng was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\etl2pcapng". See "get-help about_Command_Precedence" for more details.
```

```
> etl2pcapng.exe -?
etl2pcapng.exe : The term 'etl2pcapng.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ etl2pcapng.exe -?
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (etl2pcapng.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

```
>  .\etl2pcapng.exe -?
etl2pcapng <infile> <outfile>
Converts a packet capture from etl to pcapng format.
```


I did a rework of the module recently, but haven't touched that part of code. Version 2021.4.7 is the current version. Can you test to see if you get the error with that version?

**Comment by ToddMaxey** [comment]
Will look at on Friday when I get back


Sent from a mobile device.
Expect typographical errors and inevitable miscommunications.

My apologies in advance.

No trees were utilized in the posting of this message. However a enormous number of electrons were terribly inconvenienced.

________________________________

**Comment by JamesKehr** [comment]
I have updated the repro with several fixes. Update the contents of Convert-Etl2Pcapng.psm1 with the code here:

https://raw.githubusercontent.com/microsoft/Convert-Etl2Pcapng/main/Convert-Etl2Pcapng.psm1

You can use this command to find where the module is installed:

```powershell
(Get-Module -ListAvailable Convert-Etl2Pcapng).Path
```

Restart PowerShell after updating the code. Run Unregister-Etl2Pcapng and then Register-Etl2Pcapng to update the right-click registration.

If you get an error saying "The 'Convert-Etl2Pcapng' command was found in the module 'Convert-Etl2Pcapng', but the module
could not be loaded." you will need to run Unblock-File against Convert-Etl2pcapng.psm1.

I will update the module on PowerShell Gallery after testing a few more things.

**Comment by JamesKehr** [comment]
The PowerShell Gallery has been updated with a module version that should resolve this, and a few other, issues.
