### ISSUE TITLE
Update-Etl2Pcapng failed due to "v1.7.0" string cannot be converted to [version] type 

### ISSUE THREAD

**Issue by luyaof** [microsoft/Convert-Etl2Pcapng#5]
Update-Etl2Pcapng  -Force
Cannot convert value "v1.7.0" to type "System.Version". Error: "Input string was not in a correct format."

This caused Convert-Etl2Pcapng failed if update required.

**Comment by JamesKehr** [comment]
I have updated the repro with a fix. Update the contents of Convert-Etl2Pcapng.psm1 with the code here:

https://raw.githubusercontent.com/microsoft/Convert-Etl2Pcapng/main/Convert-Etl2Pcapng.psm1

You can use this command to find where the module is installed:

```powershell
(Get-Module -ListAvailable Convert-Etl2Pcapng).Path
```

Restart PowerShell after updating the code. Run Unregister-Etl2Pcapng and then Register-Etl2Pcapng to update the right-click registration.

If you get an error saying "The 'Convert-Etl2Pcapng' command was found in the module 'Convert-Etl2Pcapng', but the module
could not be loaded." you will need to run Unblock-File against Convert-Etl2pcapng.psm1.

I will update the module on PowerShell Gallery after testing a few more things.

**Comment by JamesKehr** [comment]
Resolved with PR #6.
